# Generated by Django 2.2.4 on 2019-12-09 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='recipes'),
        ),
        migrations.CreateModel(
            name='Steps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name="Numéro d'étape")),
                ('text', models.CharField(max_length=50, verbose_name='Détail')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='cookie.Recipe', verbose_name='Recette')),
            ],
        ),
    ]
