# Generated by Django 2.2.4 on 2019-12-23 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookie', '0005_shop_contributors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='shop',
            name='contributors',
        ),
        migrations.AddField(
            model_name='shop',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='shop', to=settings.AUTH_USER_MODEL),
        ),
    ]
