# Generated by Django 2.2.4 on 2020-02-03 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookie', '0007_auto_20191230_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopListDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_value', models.IntegerField(default=0)),
                ('bought_status', models.CharField(choices=[('PARTIAL', 'PARTIAL'), ('COMPLETE', 'COMPLETE'), ('NOTTOUCH', 'COMPLETE')], default='NOTTOUCH', max_length=10)),
                ('measure_type', models.CharField(choices=[('x', 'x'), ('kilogramme', 'kilogramme'), ('gramme', 'gramme'), ('litre', 'litre'), ('centilitre', 'centilitre'), ('millilitre', 'millilitre')], max_length=20, verbose_name='Type de mesure')),
                ('total_quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_list_detail', to='cookie.Article')),
            ],
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='article',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='bought_status',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='bought_value',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='measure_type',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='shoplist',
            name='contributors',
            field=models.ManyToManyField(blank=True, related_name='shop_list', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoplist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoplist',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='cookie.Recipe'),
        ),
        migrations.AddField(
            model_name='shoplist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='recipes/'),
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.AddField(
            model_name='shoplistdetail',
            name='shop_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_content', to='cookie.ShopList'),
        ),
    ]
