# Generated by Django 2.2.4 on 2020-08-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0009_auto_20200216_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=300)),
                ('measure_type', models.CharField(choices=[('x', 'x'), ('kilogramme', 'kilogramme'), ('gramme', 'gramme'), ('litre', 'litre'), ('centilitre', 'centilitre'), ('millilitre', 'millilitre'), ('Cuillère à café', 'Cuillère à café'), ('centilitre', 'centilitre')], max_length=20, verbose_name='Type de mesure')),
            ],
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure_type',
            field=models.CharField(choices=[('x', 'x'), ('kilogramme', 'kilogramme'), ('gramme', 'gramme'), ('litre', 'litre'), ('centilitre', 'centilitre'), ('millilitre', 'millilitre'), ('Cuillère à café', 'Cuillère à café'), ('centilitre', 'centilitre')], max_length=20, verbose_name='Type de mesure'),
        ),
        migrations.AlterField(
            model_name='shoppingingredientlist',
            name='measure_type',
            field=models.CharField(choices=[('x', 'x'), ('kilogramme', 'kilogramme'), ('gramme', 'gramme'), ('litre', 'litre'), ('centilitre', 'centilitre'), ('millilitre', 'millilitre'), ('Cuillère à café', 'Cuillère à café'), ('centilitre', 'centilitre')], max_length=20, verbose_name='Type de mesure'),
        ),
    ]
