# Generated by Django 2.2.4 on 2020-08-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0011_auto_20200802_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measure_type',
            field=models.CharField(choices=[('x', 'x'), ('milligramme', 'milligramme'), ('kilogramme', 'kilogramme'), ('gramme', 'gramme'), ('litre', 'litre'), ('centilitre', 'centilitre'), ('millilitre', 'millilitre'), ('Cuillère à café', 'Cuillère à café'), ('Cuillère à soupe', 'Cuillère à soupe')], max_length=20, verbose_name='Type de mesure'),
        ),
        migrations.AlterField(
            model_name='matchkeywords',
            name='measure_type',
            field=models.CharField(choices=[('x', 'x'), ('milligramme', 'milligramme'), ('kilogramme', 'kilogramme'), ('gramme', 'gramme'), ('litre', 'litre'), ('centilitre', 'centilitre'), ('millilitre', 'millilitre'), ('Cuillère à café', 'Cuillère à café'), ('Cuillère à soupe', 'Cuillère à soupe')], max_length=20, verbose_name='Type de mesure'),
        ),
        migrations.AlterField(
            model_name='shoppingingredientlist',
            name='measure_type',
            field=models.CharField(choices=[('x', 'x'), ('milligramme', 'milligramme'), ('kilogramme', 'kilogramme'), ('gramme', 'gramme'), ('litre', 'litre'), ('centilitre', 'centilitre'), ('millilitre', 'millilitre'), ('Cuillère à café', 'Cuillère à café'), ('Cuillère à soupe', 'Cuillère à soupe')], max_length=20, verbose_name='Type de mesure'),
        ),
    ]
