# Generated by Django 2.2.4 on 2020-08-02 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0013_auto_20200802_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchkeywords',
            name='order',
            field=models.IntegerField(default=99, verbose_name='Ordre de recherche'),
        ),
    ]
