# Generated by Django 2.2.4 on 2020-08-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0014_matchkeywords_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='how_many_found_in_recipes',
            field=models.IntegerField(default=0),
        ),
    ]
