# Generated by Django 2.2.4 on 2020-08-02 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0011_auto_20200701_0642'),
        ('cookie', '0015_article_how_many_found_in_recipes'),
    ]

    operations = [
    ]
