# Generated by Django 2.2.4 on 2020-08-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0016_merge_20200802_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoplistdetail',
            name='article',
        ),
        migrations.RemoveField(
            model_name='shoplistdetail',
            name='shop_list',
        ),
        migrations.AlterField(
            model_name='article',
            name='how_many_found_in_recipes',
            field=models.IntegerField(default=1, verbose_name='Occurances'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measure_type',
            field=models.CharField(choices=[('x', 'x'), ('Milligramme', 'Milligramme'), ('Kilogramme', 'Kilogramme'), ('Gramme', 'Gramme'), ('Litre', 'Litre'), ('Centilitre', 'Centilitre'), ('Millilitre', 'Millilitre'), ('Cuillère à café', 'Cuillère à café'), ('Cuillère à soupe', 'Cuillère à soupe'), ('GOUSSE', 'GOUSSE')], max_length=20, verbose_name='Type de mesure'),
        ),
        migrations.AlterField(
            model_name='matchkeywords',
            name='measure_type',
            field=models.CharField(choices=[('x', 'x'), ('Milligramme', 'Milligramme'), ('Kilogramme', 'Kilogramme'), ('Gramme', 'Gramme'), ('Litre', 'Litre'), ('Centilitre', 'Centilitre'), ('Millilitre', 'Millilitre'), ('Cuillère à café', 'Cuillère à café'), ('Cuillère à soupe', 'Cuillère à soupe'), ('GOUSSE', 'GOUSSE')], max_length=20, verbose_name='Type de mesure'),
        ),
        migrations.AlterField(
            model_name='shoppingingredientlist',
            name='measure_type',
            field=models.CharField(choices=[('x', 'x'), ('Milligramme', 'Milligramme'), ('Kilogramme', 'Kilogramme'), ('Gramme', 'Gramme'), ('Litre', 'Litre'), ('Centilitre', 'Centilitre'), ('Millilitre', 'Millilitre'), ('Cuillère à café', 'Cuillère à café'), ('Cuillère à soupe', 'Cuillère à soupe'), ('GOUSSE', 'GOUSSE')], max_length=20, verbose_name='Type de mesure'),
        ),
        migrations.DeleteModel(
            name='ShopList',
        ),
        migrations.DeleteModel(
            name='ShopListDetail',
        ),
    ]
