# Generated by Django 2.2.4 on 2019-10-26 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('categories', models.ManyToManyField(blank=True, to='cookie.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recipes', models.ManyToManyField(blank=True, to='cookie.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bought_status', models.CharField(choices=[('PARTIAL', 'PARTIAL'), ('COMPLETE', 'COMPLETE'), ('NOTTOUCH', 'COMPLETE')], default='NOTTOUCH', max_length=10)),
                ('total_quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('measure_type', models.CharField(choices=[('x', 'x'), ('kilogramme', 'kilogramme'), ('gramme', 'gramme'), ('litre', 'litre'), ('centilitre', 'centilitre'), ('millilitre', 'millilitre')], max_length=20, verbose_name='Type de mesure')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_list', to='cookie.Article')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_content', to='cookie.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantité')),
                ('measure_type', models.CharField(choices=[('x', 'x'), ('kilogramme', 'kilogramme'), ('gramme', 'gramme'), ('litre', 'litre'), ('centilitre', 'centilitre'), ('millilitre', 'millilitre')], max_length=20, verbose_name='Type de mesure')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cookie.Article')),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cookie.Recipe', verbose_name='Recette')),
            ],
        ),
    ]
