# Generated by Django 2.2.4 on 2019-10-19 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cookie.Article'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cookie.Recipe', verbose_name='Recette'),
        ),
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_value', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bought_status', models.CharField(choices=[('PARTIAL', 'PARTIAL'), ('COMPLETE', 'COMPLETE'), ('NOTTOUCH', 'NOTTOUCH')], default='NOTTOUCH', max_length=10)),
                ('total_quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantité')),
                ('total_weight', models.IntegerField(blank=True, null=True, verbose_name='Poids')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_list', to='cookie.Article')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list_content', to='cookie.Shop')),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='cookie.Recipe'),
        ),
    ]
