# Generated by Django 2.1.1 on 2019-08-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0002_auto_20190503_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
