# Generated by Django 2.1.4 on 2019-08-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0002_auto_20190825_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='cookie.Category'),
        ),
    ]
