# Generated by Django 2.2.4 on 2019-10-04 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0003_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('Shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cookie.Shop')),
                ('ingredients', models.ManyToManyField(to='cookie.Ingredient')),
            ],
        ),
    ]
