# Generated by Django 2.1.1 on 2019-08-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0003_recipe_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='recipe',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.ManyToManyField(null=True, to='cookie.Category'),
        ),
    ]
