# Generated by Django 2.2.4 on 2019-10-06 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0004_shoplist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cookie.Article'),
        ),
    ]
