# Generated by Django 2.2.4 on 2019-10-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0005_auto_20191006_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoplist',
            name='is_bought',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoplist',
            name='value_bought',
            field=models.IntegerField(null=True),
        ),
    ]
