# Generated by Django 2.2.4 on 2019-10-18 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookie', '0006_auto_20191008_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoplist',
            old_name='value_bought',
            new_name='bought_value',
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='Shop',
        ),
        migrations.AddField(
            model_name='shoplist',
            name='shop',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_list', to='cookie.Shop'),
        ),
        migrations.RemoveField(
            model_name='shoplist',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='shoplist',
            name='ingredients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cookie.Ingredient'),
        ),
    ]
